// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mlbL7FkQ-GQtaMz-UextO5XWKPUjG_Q',
    appId: '1:80710857666:web:a7991fb21e5ebddbe79c5b',
    messagingSenderId: '80710857666',
    projectId: 'punurunbb',
    authDomain: 'punurunbb.firebaseapp.com',
    databaseURL: 'https://punurunbb-default-rtdb.firebaseio.com',
    storageBucket: 'punurunbb.firebasestorage.app',
    measurementId: 'G-RH5R1GQJL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi6wU0frho8oRWi85gNu9ESNEiohPLtiY',
    appId: '1:80710857666:android:dd9d7c03f476e774e79c5b',
    messagingSenderId: '80710857666',
    projectId: 'punurunbb',
    databaseURL: 'https://punurunbb-default-rtdb.firebaseio.com',
    storageBucket: 'punurunbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HkqGToUcYFdAndvPUDb2vcmADTY9jm0',
    appId: '1:80710857666:ios:f8baa91fcd7558fbe79c5b',
    messagingSenderId: '80710857666',
    projectId: 'punurunbb',
    databaseURL: 'https://punurunbb-default-rtdb.firebaseio.com',
    storageBucket: 'punurunbb.firebasestorage.app',
    iosBundleId: 'com.example.projectpember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3HkqGToUcYFdAndvPUDb2vcmADTY9jm0',
    appId: '1:80710857666:ios:f8baa91fcd7558fbe79c5b',
    messagingSenderId: '80710857666',
    projectId: 'punurunbb',
    databaseURL: 'https://punurunbb-default-rtdb.firebaseio.com',
    storageBucket: 'punurunbb.firebasestorage.app',
    iosBundleId: 'com.example.projectpember',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mlbL7FkQ-GQtaMz-UextO5XWKPUjG_Q',
    appId: '1:80710857666:web:468718dcffaa7729e79c5b',
    messagingSenderId: '80710857666',
    projectId: 'punurunbb',
    authDomain: 'punurunbb.firebaseapp.com',
    databaseURL: 'https://punurunbb-default-rtdb.firebaseio.com',
    storageBucket: 'punurunbb.firebasestorage.app',
    measurementId: 'G-665ZYHPNWT',
  );
}
